build: ai_path_random_placement_strategy.o

clean:
	rm -f $(wildcard *.o)

ai_path_random_placement_strategy.o: ai_path_random_placement_strategy.cpp
	$(CXX) $(CXXFLAGS) $(INCLUDES) -c -o $@ $^

FORCE: